name: Deploy Lambda Function

on:
  push:
    branches: [ development, release, main ]

env:
    ENVIRONMENT: dev
    AWS_REGION: us-east-2
    ECR_REPOSITORY: radx-publicationscript

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - name: Set env to test
        if: endsWith(github.ref, '/release')
        run: |
          echo "ENVIRONMENT=test" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

      - name: Set env to production
        if: endsWith(github.ref, '/main')
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "AWS_REGION=us-west-2" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY/$ENVIRONMENT:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY/$ENVIRONMENT:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY/$ENVIRONMENT:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update Lambda function code 
        env:
          image: ${{ steps.build-image.outputs.image }}
        run: |
          aws lambda update-function-code --function-name RADx-PublicationScript --image-uri $image
